### ISSUE TITLE
webpack throw erorr about 'fs' module

### ISSUE THREAD

**Issue by asfktz** [josephsavona/valuable#9]
while building with webpack, I'm getting this error:

```
ERROR in ./~/valuable/~/lazy.js/lazy.node.js
Module not found: Error: Cannot resolve module 'fs' 
  in /Users/asafkatz/Documents/dev/react-cart/node_modules/valuable/node_modules/lazy.js
@ ./~/valuable/~/lazy.js/lazy.node.js 1:13-26
```

it happens even if I just call:

```
var Valuable = require('valuable');
```

using the latest version: 0.3.2

for what its worth, this is my webpack.config.js file

```
// webpack.config.js
module.exports = {
    entry: './app/app.jsx',
    output: {
        path : './app',
        filename: 'bundle.js',
    },
    cache : true,
    watch : true,
    devtool: "eval",
    module: {
        loaders: [
            {
                test: /\.jsx$/,
                loader: 'jsx-loader?harmony'
            }
        ]
    },
    resolve : {
        extensions : ['', '.js', '.jsx']
    }
};

```

**Comment by amypellegrini** [comment]
I had this problem with webpack, but I solved adding:

```
target: 'node',
```

to my webpack.config.js as described [here ](http://jlongster.com/Backend-Apps-with-Webpack--Part-I)

**Comment by tbogatchev** [comment]
I'm still receiving the fs module error after adding target: 'node' and node: {fs: 'empty'}, any other ideas?
Running node 7.9.0
Webpack 2.3.3

**Comment by josephsavona** [comment]
I'm no longer maintaining this repository. I'd suggest alternate approaches to state management - Redux is great, I'm less familiar w Mobx but it is conceptually closer to valuable.

**Comment by amedley** [comment]
Don't target: 'node' AND node: {fs: 'empty'}
Only target: 'node', do not do both.

**Comment by vurumadla** [comment]
i am facing this issue during building through dev.js. can anyone sugegst the solution.



WARNING in ./~/ipfs-js/~/ipfs-api/dist/ipfsapi.min.js
Critical dependencies:
1:461-468 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/ipfs-js/~/ipfs-api/dist/ipfsapi.min.js 1:461-468

ERROR in ./~/ipfs-api/lib/get-files-stream.js
Module not found: Error: Cannot resolve module 'fs' in /home/centos/PrivateSecurities1/node_modules/ipfs-api/lib
 @ ./~/ipfs-api/lib/get-files-stream.js 33:11-24

ERROR in ./~/glob/glob.js
Module not found: Error: Cannot resolve module 'fs' in /home/centos/PrivateSecurities1/node_modules/glob
 @ ./~/glob/glob.js 43:9-22

ERROR in ./~/glob/sync.js
Module not found: Error: Cannot resolve module 'fs' in /home/centos/PrivateSecurities1/node_modules/glob
 @ ./~/glob/sync.js 4:9-22

ERROR in ./~/ipfs-merkle-dag/lib/dag-node.js
Module not found: Error: Cannot resolve module 'fs' in /home/centos/PrivateSecurities1/node_modules/ipfs-merkle-dag/lib
 @ ./~/ipfs-merkle-dag/lib/dag-node.js 9:9-22

ERROR in ./~/fs.realpath/index.js
Module not found: Error: Cannot resolve module 'fs' in /home/centos/PrivateSecurities1/node_modules/fs.realpath
 @ ./~/fs.realpath/index.js 8:9-22

**Comment by mihail-hrushev** [comment]
I found my answer for such issues here :
https://jlongster.com/Backend-Apps-with-Webpack--Part-I

**Comment by omar-dulaimi** [comment]
For me what caused this was installing dotenv-webpack and then uninstalling it without removing the lines that reference it like imports. Hope this helps someone. Setting both  node: { fs: 'empty'} and target: 'node' helped me find the the problem.
